bash scripts with google style guide

diff --git a/src/bin/image-sitter b/src/bin/image-sitter
--- a/src/bin/image-sitter
+++ b/src/bin/image-sitter
@@ -4,13 +4,13 @@
 source /usr/lib/image-sitter/image-sitter-config
 
 if [[ $# -eq 0 ]]; then
-    echo "Usage: $(basename "$0") group [group ...]" >&2
-    exit 0
+  echo "Usage: $(basename "$0") group [group ...]" >&2
+  exit 0
 fi
 
 if ! command -v "$IMAGE_SITTER_CLI" &>/dev/null; then
-    echo "$IMAGE_SITTER_CLI could not be found"
-    exit 1
+  echo "$IMAGE_SITTER_CLI could not be found" >&2
+  exit 1
 fi
 
 echo.magenta "[Delete If Exists]"
diff --git a/src/bin/image-sitter-delete-if-exists b/src/bin/image-sitter-delete-if-exists
--- a/src/bin/image-sitter-delete-if-exists
+++ b/src/bin/image-sitter-delete-if-exists
@@ -4,35 +4,35 @@
 source /usr/lib/image-sitter/image-sitter-config
 
 if [[ $# -eq 0 ]]; then
-    echo "Usage: $(basename "$0") group [group ...]" >&2
-    exit 0
+  echo "Usage: $(basename "$0") group [group ...]" >&2
+  exit 0
 fi
 
 if ! command -v "$IMAGE_SITTER_CLI" &>/dev/null; then
-    echo "$IMAGE_SITTER_CLI could not be found"
-    exit 1
+  echo "$IMAGE_SITTER_CLI could not be found" >&2
+  exit 1
 fi
 for group in "$@"; do
-    DIR=$IMAGE_SITTER_HOME/$group/$DIRECTORY_DELETE_IF_EXISTS
-    [[ -d $DIR ]] || continue
+  DIR=$IMAGE_SITTER_HOME/$group/$DIRECTORY_DELETE_IF_EXISTS
+  [[ -d $DIR ]] || continue
 
-    echo.blue "[$group]"
-    find "$DIR" -type f | sort | while read -r fileName; do
+  echo.blue "[$group]"
+  find "$DIR" -type f | sort | while read -r fileName; do
 
-        while read -r docker_url; do
-            [[ $docker_url =~ ^[[:space:]]*#.* ]] && continue
-            [[ $docker_url =~ ^[[:space:]]*$ ]] && continue
+    while read -r docker_url; do
+      [[ $docker_url =~ ^[[:space:]]*#.* ]] && continue
+      [[ $docker_url =~ ^[[:space:]]*$ ]] && continue
 
-            TAG1=$($IMAGE_SITTER_CLI images -q "$docker_url" 2>/dev/null)
+      TAG1=$($IMAGE_SITTER_CLI images -q "$docker_url" 2>/dev/null)
 
-            if [[ "$TAG1" == "" ]]; then
-                echo.yellow "Not Found: $docker_url"
+      if [[ "$TAG1" == "" ]]; then
+        echo.yellow "Not Found: $docker_url"
 
-            else
-                echo.green "$IMAGE_SITTER_CLI rmi $docker_url"
-                $IMAGE_SITTER_CLI rmi "$docker_url"
-            fi
-        done <"$fileName"
+      else
+        echo.green "$IMAGE_SITTER_CLI rmi $docker_url"
+        $IMAGE_SITTER_CLI rmi "$docker_url"
+      fi
+    done <"$fileName"
 
-    done
+  done
 done
diff --git a/src/bin/image-sitter-init b/src/bin/image-sitter-init
--- a/src/bin/image-sitter-init
+++ b/src/bin/image-sitter-init
@@ -4,15 +4,15 @@
 source /usr/lib/image-sitter/image-sitter-config
 
 if [[ $# -ne 1 ]]; then
-    echo "Usage: $(basename "$0") group" >&2
-    exit 0
+  echo "Usage: $(basename "$0") group" >&2
+  exit 0
 fi
 
 GROUP=$1
 
-if [[ -d "$IMAGE_SITTER_HOME/$GROUP" ]] ; then
-    echo "Error: The directory $IMAGE_SITTER_HOME/$GROUP already exists." >&2
-    exit 1
+if [[ -d "$IMAGE_SITTER_HOME/$GROUP" ]]; then
+  echo "Error: The directory $IMAGE_SITTER_HOME/$GROUP already exists." >&2
+  exit 1
 fi
 
 mkdir -v -p "$IMAGE_SITTER_HOME/$GROUP"
diff --git a/src/bin/image-sitter-pull-always b/src/bin/image-sitter-pull-always
--- a/src/bin/image-sitter-pull-always
+++ b/src/bin/image-sitter-pull-always
@@ -4,28 +4,28 @@
 source /usr/lib/image-sitter/image-sitter-config
 
 if [[ $# -eq 0 ]]; then
-    echo "Usage: $(basename "$0") group [group ...]" >&2
-    exit 0
+  echo "Usage: $(basename "$0") group [group ...]" >&2
+  exit 0
 fi
 
 if ! command -v "$IMAGE_SITTER_CLI" &>/dev/null; then
-    echo "$IMAGE_SITTER_CLI could not be found"
-    exit 1
+  echo "$IMAGE_SITTER_CLI could not be found" >&2
+  exit 1
 fi
 for group in "$@"; do
-    DIR=$IMAGE_SITTER_HOME/$group/$DIRECTORY_PULL_ALWAYS
-    [[ -d $DIR ]] || continue
+  DIR=$IMAGE_SITTER_HOME/$group/$DIRECTORY_PULL_ALWAYS
+  [[ -d $DIR ]] || continue
 
-    echo.blue "[$group]"
-    find "$DIR" -type f | sort | while read -r fileName; do
+  echo.blue "[$group]"
+  find "$DIR" -type f | sort | while read -r fileName; do
 
-        while read -r docker_url; do
-            [[ $docker_url =~ ^[[:space:]]*#.* ]] && continue
-            [[ $docker_url =~ ^[[:space:]]*$ ]] && continue
+    while read -r docker_url; do
+      [[ $docker_url =~ ^[[:space:]]*#.* ]] && continue
+      [[ $docker_url =~ ^[[:space:]]*$ ]] && continue
 
-            echo.green "$IMAGE_SITTER_CLI pull $docker_url"
-            $IMAGE_SITTER_CLI pull "$docker_url"
-        done <"$fileName"
+      echo.green "$IMAGE_SITTER_CLI pull $docker_url"
+      $IMAGE_SITTER_CLI pull "$docker_url"
+    done <"$fileName"
 
-    done
+  done
 done
